name: React Build and Deploy
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '**.md'
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      REACT_APP_APIURL: ${{ secrets.API_URL }}
    steps:
      - uses: actions/checkout@v2
      # - name: User Node.js v16
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      #     cache: 'npm'
      # - name: Install dependencies
      #   run: npm install
      # - name: Build the React app
      #   run: CI= npm run build
      # - name: Prepare to SSH into the VPS
      # - run: mkdir ~/.ssh
      # - run: 'echo "$SSH_KEY" >> ~/.ssh/id_deploy_machine'
      # - run: 'chmod 400 ~/.ssh/id_deploy_machine'
      # - run: 'echo -e "Host deploy-machine\n\tUser $SSH_USER\n\tHostName $SSH_HOST\n\tIdentityFile ~/.ssh/id_deploy_machine\n\tStrictHostKeyChecking No" >> ~/.ssh/config'
      # - run: 'rsync ${{ github-workspace }}/'
      - run: ls -al
      - run: echo "🍏 This job's status is ${{ job.status }}."
